title: Jayson Piper # your name (or website title) here
logo: "/thumbnail_IMG_0653.jpg" # your photo (or logo) heredescription: > # your text below (remove <br> elements if you don't need line breaks)
description: >  
  Seeking a data analyst post or similar position. 
  Currently attending JustIT data bootcamp. 
  www.linkedin.com/in/jayson-piper-465436244
  

